### ISSUE TITLE
Cant clone repository

### ISSUE THREAD

**Issue by ghost** [mprey/steam-account-creator#1]
https://i.gyazo.com/e4a9e9c53d17cbf7aaa8b707756025ce.png

Says I dont have permissions, what I can do?

Thanks.

**Comment by mprey** [comment]
it looks like you don't have SSH keys set up with your VPS/PC. if you do not want to do that, feel free to clone the repo with this command over HTTPS instead 

```
$ git clone https://github.com/mprey/steam-account-creator.git
```
