### ISSUE TITLE
Steps to reproduce in a function

### ISSUE THREAD

**Issue by Schknheit** [mprey/steam-account-creator#3]
Hello, I see that you created a `client.on` and I was wondering if I could call this in a function? I really have no clue how!. Thanks for the script!.

**Comment by mprey** [comment]
You cannot call any functions like that, they are only called by the Steam module when the event occurs. You should try to rewrite your app's logic so you can avoid relying on `client.on` functions to be called.

**Comment by Schknheit** [comment]
What does this `client.on` does actually?

**Comment by Schknheit** [comment]
I'm trying to after creating the accounts getting off in steam and right after getting back on again, So thus I would call this `client.on` as a function

**Comment by mprey** [comment]
`client.on` is a listener function that is called when events are emitted. If you want to log off of steam and log back on, you would call `client.logOff` and `client.logOn`

**Comment by Schknheit** [comment]
I'm using a fork of yours, https://github.com/michalani/steam-account-creator and I already did a way to automatic shuffle the email adress, but can't figure out this logOn and logOff because somewho steam gives me error 84 after creating two accounts. I tried like, putting all those client logOns inside a function that is called when the script starts and inside the createAccount function, tell logOff and then call the beginning of the whole script again, but It keeps telling me that I'm still logged even though the logOff method was already called, so I'm really confused.
